apiVersion: v1
name: mysql
namespace: roboshop # this is the namespace where the chart will be deployed
version: 0.0.1   # this the chart version
description: this is the customised helm chart for mysql
appVersion: v1